export { default as Navbar } from "./Navbar/Navbar";
export { default as Hero } from "./Hero/Hero";
export { default as About } from "./About/About";
export { default as Popular } from "./Popular/Popular";
export { default as ProductList } from "./ProductList/ProductList";
export { default as Locations } from "./Locations/Locations";
export { default as Testimonials } from "./Testimonials/Testimonials";
export { default as Newsletter } from "./Newsletter/Newsletter";
export { default as Footer } from "./Footer/Footer";
